import { useState } from 'react'
import {
  HiOutlineArrowDownTray,
  HiOutlineClipboardDocumentCheck,
  HiOutlineCheck,
  HiOutlineCodeBracket,
  HiOutlineArrowPath,
  HiOutlineCheckCircle,
  HiOutlineDocumentText,
} from 'react-icons/hi2'
import Card from '../common/Card'
import Button from '../common/Button'
import Typography from '../common/Typography'

export default function DownloadSchemaCard({
  sqlContent = '',
  fileName = 'schema.sql',
  prompt = '',
  onReset,
}) {
  const [copied, setCopied] = useState(false)
  const [showPreview, setShowPreview] = useState(false)

  const fileSizeKb = (new Blob([sqlContent]).size / 1024).toFixed(2)

  const handleDownload = () => {
    const blob = new Blob([sqlContent], { type: 'application/sql' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = fileName
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(sqlContent)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch (err) {
      console.error('Failed to copy SQL content:', err)
    }
  }

  return (
    <Card className="rounded-4xl border-primary/10 bg-surface/90 p-5 shadow-xl shadow-primary/8 sm:p-6 lg:p-7">
      <div className="flex flex-col gap-6">
        {/* Status Header */}
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="flex min-w-0 items-start gap-4">
            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-[18px] bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 shadow-sm">
              <HiOutlineCheckCircle className="h-7 w-7" aria-hidden="true" />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <Typography as="h2" variant="h3">
                  Schema Ready for Download
                </Typography>
                <span className="inline-flex items-center rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-xs font-semibold text-emerald-700 dark:text-emerald-400">
                  Ready
                </span>
              </div>
              <Typography as="p" variant="muted" className="mt-1">
                Your database schema script was successfully generated by the backend architect.
              </Typography>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              onClick={onReset}
              leftIcon={<HiOutlineArrowPath className="h-4 w-4" />}
              className="h-10 px-4 text-xs font-medium"
            >
              Generate New
            </Button>
          </div>
        </div>

        {/* File Information Card */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 rounded-2xl border border-primary/10 bg-background/60 p-4 sm:px-5">
          <div className="flex items-center gap-3.5 min-w-0">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">
              <HiOutlineDocumentText className="h-5 w-5" aria-hidden="true" />
            </div>
            <div className="min-w-0">
              <p className="font-semibold text-primary truncate text-base">{fileName}</p>
              <p className="text-xs text-secondary">
                Size: <span className="font-medium text-primary">{fileSizeKb} KB</span>
                {prompt ? ` • Prompt: "${prompt.slice(0, 45)}${prompt.length > 45 ? '...' : ''}"` : ''}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2.5 w-full sm:w-auto">
            <Button
              variant="primary"
              onClick={handleDownload}
              leftIcon={<HiOutlineArrowDownTray className="h-5 w-5" />}
              className="flex-1 sm:flex-initial"
            >
              Download SQL File
            </Button>

            <Button
              variant="outline"
              onClick={handleCopy}
              leftIcon={
                copied ? (
                  <HiOutlineCheck className="h-5 w-5 text-emerald-600" />
                ) : (
                  <HiOutlineClipboardDocumentCheck className="h-5 w-5" />
                )
              }
              className="px-4"
              title="Copy to clipboard"
            >
              {copied ? 'Copied' : 'Copy'}
            </Button>

            <Button
              variant="outline"
              onClick={() => setShowPreview((prev) => !prev)}
              leftIcon={<HiOutlineCodeBracket className="h-5 w-5" />}
              className="px-4"
              title={showPreview ? 'Hide Code' : 'Preview Code'}
            >
              {showPreview ? 'Hide' : 'Preview'}
            </Button>
          </div>
        </div>

        {/* Code Preview Drawer / Box */}
        {showPreview && (
          <div className="mt-1 space-y-2">
            <div className="flex items-center justify-between text-xs text-secondary font-mono px-1">
              <span>SQL Preview ({fileName})</span>
              <span>{sqlContent.split('\n').length} lines</span>
            </div>
            <div className="relative max-h-80 overflow-y-auto rounded-2xl border border-primary/10 bg-[#1E1E2E] p-4 text-xs font-mono text-[#CDD6F4] shadow-inner leading-relaxed">
              <pre className="whitespace-pre-wrap break-words">{sqlContent}</pre>
            </div>
          </div>
        )}
      </div>
    </Card>
  )
}
